### PR TITLE
copy existing typings from definitely typed

### PR DESCRIPTION
**Pull request by gregra81**
Copied type definitions from DefinitelyTyped

### CODE REVIEW

**Review by arutkowski00 — APPROVED** [review]

**Comment by arutkowski00** [comment]
Nice 👌🏻

**Comment by josh-** [comment]
@gregra81 would you consider approving this PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64422 which removes the types from the DefinitelyTyped? Hopefully that speeds up their removal from there now that you've bundled in the types here.

**Comment by gregra81** [comment]
@josh- approved

**Comment by josh-** [comment]
Amazing, thankyou!

**Pull request merged**
